---
- name: Copy the join command to server location
  copy: src=control_plane_cert_secret dest=/tmp/join-command.sh mode=0777

- name: Join the node to cluster
  command: sh /tmp/join-command.sh
  changed_when: false
