---
- include_tasks: variables.yml

- include_tasks: create-user.yml

- include_tasks: setup-Amazon.yml
  when: ansible_distribution == "Amazon"

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == "RedHat" and ansible_distribution != "Amazon"

- include_tasks: setup-Debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: initialize-master.yml
  when: k8s_node_role == "master"

- include_tasks: initialize-worker.yml
  when: k8s_node_role == "worker"

- include_tasks: install-extras.yml
