---
- include_tasks: variables.yml

- include_tasks: create-user.yml

- include_tasks: setup-docker-Amazon.yml
  when: ansible_distribution == "Amazon"

- include_tasks: setup-docker-RedHat.yml
  when: ansible_os_family == "RedHat" and ansible_distribution != "Amazon"

- include_tasks: setup-docker-Debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: setup-prepare-RedHat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: setup-prepare-Debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: setup-k8s-RedHat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: setup-k8s-Debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: initialize-main-master.yml
  when: k8s_node_role == "main-master"

- include_tasks: initialize-backup-master.yml
  when: k8s_node_role == "backup-master"

- include_tasks: initialize-worker.yml
  when: k8s_node_role == "worker"

- include_tasks: install-extras.yml
