---
- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add Docker repo key
  apt_key:
    url: "{{ k8s_docker_key }}"
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: "{{ k8s_docker_repo }}"
    state: present

- name: Install docker and its dependecies
  apt:
    name: "{{ k8s_docker_packages }}"
    state: present
    update_cache: true
  notify:
    - docker status

- name: Add kube user to docker group
  user:
    name: kube
    group: docker
