---
- name: Install pre-requirements
  yum:
    name:
      - openssl
      - which
      - tar
    state: present
    update_cache: true

- name: Enable Docker repository
  command: "amazon-linux-extras install -y epel docker"
  changed_when: false

- name: Install Docker
  yum:
    name:
      - docker
      - containerd
    state: present
    update_cache: true

- name: Start Docker
  service:
    name: docker
    state: started

- name: Disable SWAP
  command: swapoff -a
  changed_when: false

- name: Check /etc/fstab exists
  stat:
    path: /etc/fstab
  register: fstab

- name: Disable SWAP in fstab
  replace:
    path: /etc/fstab
    regexp: '^(.+?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  when: fstab.stat.exists

- name: modprobe br_netfilter
  command: modprobe br_netfilter
  changed_when: false
  ignore_errors: true

- name: Ensure net.bridge.bridge-nf-call-ip6tables is set to 1
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    state: present
  ignore_errors: true

- name: Ensure net.bridge.bridge-nf-call-iptables is set to 1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present
  ignore_errors: true

- name: Add Kubernetes YUM repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repository
    baseurl: "{{ k8s_kubernetes_repo }}"
    gpgkey: "{{ k8s_kubernetes_key }}"
    gpgcheck: true

- name: Install Kubernetes binaries
  yum:
    name: "{{ k8s_kubernetes_packages }}"
    state: present
    update_cache: true

- name: Start kubelet
  service:
    name: kubelet
    enabled: true
    state: started
