---
- name: Include OS-specific variables.
  include_vars: "{{ lookup('first_found', possible_files) }}"
  vars:
    possible_files:
      - "vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
      - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "vars/{{ ansible_distribution }}.yml"
      - "vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
      - "vars/{{ ansible_os_family }}.yml"

- name: Define k8s_docker_repo
  set_fact:
    k8s_docker_repo: "{{ __k8s_docker_repo | default('') }}"
  when: k8s_docker_repo is not defined

- name: Define k8s_docker_key
  set_fact:
    k8s_docker_key: "{{ __k8s_docker_key | default('') }}"
  when: k8s_docker_key is not defined

- name: Define k8s_kubernetes_repo
  set_fact:
    k8s_kubernetes_repo: "{{ __k8s_kubernetes_repo | default('') }}"
  when: k8s_kubernetes_repo is not defined

- name: Define k8s_kubernetes_repo_key
  set_fact:
    k8s_kubernetes_repo_key: "{{ __k8s_kubernetes_repo_key | default('') }}"
  when: k8s_kubernetes_repo_key is not defined

- name: Define k8s_update_iptable_bridge_rules
  set_fact:
    k8s_update_iptable_bridge_rules: "{{ __k8s_update_iptable_bridge_rules | default(false) }}"
  when: k8s_update_iptable_bridge_rules is not defined

- name: Define k8s_update_selinux
  set_fact:
    k8s_update_selinux: "{{ __k8s_update_selinux | default(false) }}"
  when: k8s_update_selinux is not defined

- name: Define k8s_kubelet_config
  set_fact:
    k8s_kubelet_config: "{{ __k8s_kubelet_config | default('') }}"
  when: k8s_kubelet_config is not defined
