---
- name: Include OS-specific variables.
  include_vars: "{{ lookup('first_found', possible_files) }}"
  vars:
    possible_files:
      - "vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
      - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "vars/{{ ansible_distribution }}.yml"
      - "vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
      - "vars/{{ ansible_os_family }}.yml"

- name: Define k8s_docker_repo
  set_fact:
    k8s_docker_repo: "{{ __k8s_docker_repo | default('') }}"
  when: k8s_docker_repo is not defined

- name: Define k8s_docker_key
  set_fact:
    k8s_docker_key: "{{ __k8s_docker_key | default('') }}"
  when: k8s_docker_key is not defined

- name: Define k8s_kubernetes_repo
  set_fact:
    k8s_kubernetes_repo: "{{ __k8s_kubernetes_repo }}"
  when: k8s_kubernetes_repo is not defined

- name: Define k8s_kubernetes_key
  set_fact:
    k8s_kubernetes_key: "{{ __k8s_kubernetes_key }}"
  when: k8s_kubernetes_key is not defined
